package credstore

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/joaoseixas88/lazylock/internal/atomicfile"
)

// EnvPath overrides where the file fallback writes, so tests never touch $HOME.
const EnvPath = "LAZYLOCK_SESSION"

// sessionPath resolves the file fallback. The session goes under XDG state
// rather than config or data: it is a machine-local credential that can always
// be regenerated by logging in again. Go has no os.UserStateDir.
func sessionPath() (string, error) {
	if override := os.Getenv(EnvPath); override != "" {
		return override, nil
	}
	if dir := os.Getenv("XDG_STATE_HOME"); dir != "" {
		return filepath.Join(dir, "lazylock", "session.json"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home dir: %w", err)
	}
	return filepath.Join(home, ".local", "state", "lazylock", "session.json"), nil
}

// checkFile refuses to read a session another account could have written or
// read. Loading it anyway would mean trusting a credential we cannot vouch for.
func checkFile(path string) error {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("stat session file: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%w: %s is a symlink", ErrInsecurePermissions, path)
	}
	if info.Mode().Perm()&0o077 != 0 {
		return fmt.Errorf("%w: %s is %#o", ErrInsecurePermissions, path, info.Mode().Perm())
	}
	return nil
}

func writeFile(raw []byte) error {
	path, err := sessionPath()
	if err != nil {
		return err
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	return atomicfile.Write(path, raw, 0o600)
}
